//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SidejobModel", "FK_CitiesUpdate_regionsUpdate", "regionsUpdate", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SidejobModel.regionsUpdate), "CitiesUpdate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SidejobModel.CitiesUpdate), true)]
[assembly: EdmRelationshipAttribute("SidejobModel", "FK_regionsUpdate_CountriesUpdate", "CountriesUpdate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SidejobModel.CountriesUpdate), "regionsUpdate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SidejobModel.regionsUpdate), true)]

#endregion

namespace SidejobModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SidejobEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SidejobEntities object using the connection string found in the 'SidejobEntities' section of the application configuration file.
        /// </summary>
        public SidejobEntities() : base("name=SidejobEntities", "SidejobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SidejobEntities object.
        /// </summary>
        public SidejobEntities(string connectionString) : base(connectionString, "SidejobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SidejobEntities object.
        /// </summary>
        public SidejobEntities(EntityConnection connection) : base(connection, "SidejobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AutomatedMessage> AutomatedMessages
        {
            get
            {
                if ((_AutomatedMessages == null))
                {
                    _AutomatedMessages = base.CreateObjectSet<AutomatedMessage>("AutomatedMessages");
                }
                return _AutomatedMessages;
            }
        }
        private ObjectSet<AutomatedMessage> _AutomatedMessages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AutomationEmailProblem> AutomationEmailProblems
        {
            get
            {
                if ((_AutomationEmailProblems == null))
                {
                    _AutomationEmailProblems = base.CreateObjectSet<AutomationEmailProblem>("AutomationEmailProblems");
                }
                return _AutomationEmailProblems;
            }
        }
        private ObjectSet<AutomationEmailProblem> _AutomationEmailProblems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CitiesUpdate> CitiesUpdates
        {
            get
            {
                if ((_CitiesUpdates == null))
                {
                    _CitiesUpdates = base.CreateObjectSet<CitiesUpdate>("CitiesUpdates");
                }
                return _CitiesUpdates;
            }
        }
        private ObjectSet<CitiesUpdate> _CitiesUpdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CountriesUpdate> CountriesUpdates
        {
            get
            {
                if ((_CountriesUpdates == null))
                {
                    _CountriesUpdates = base.CreateObjectSet<CountriesUpdate>("CountriesUpdates");
                }
                return _CountriesUpdates;
            }
        }
        private ObjectSet<CountriesUpdate> _CountriesUpdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<regionsUpdate> regionsUpdates
        {
            get
            {
                if ((_regionsUpdates == null))
                {
                    _regionsUpdates = base.CreateObjectSet<regionsUpdate>("regionsUpdates");
                }
                return _regionsUpdates;
            }
        }
        private ObjectSet<regionsUpdate> _regionsUpdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CanadaZipCode> CanadaZipCodes
        {
            get
            {
                if ((_CanadaZipCodes == null))
                {
                    _CanadaZipCodes = base.CreateObjectSet<CanadaZipCode>("CanadaZipCodes");
                }
                return _CanadaZipCodes;
            }
        }
        private ObjectSet<CanadaZipCode> _CanadaZipCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USAZipCode> USAZipCodes
        {
            get
            {
                if ((_USAZipCodes == null))
                {
                    _USAZipCodes = base.CreateObjectSet<USAZipCode>("USAZipCodes");
                }
                return _USAZipCodes;
            }
        }
        private ObjectSet<USAZipCode> _USAZipCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoriesFr> CategoriesFrs
        {
            get
            {
                if ((_CategoriesFrs == null))
                {
                    _CategoriesFrs = base.CreateObjectSet<CategoriesFr>("CategoriesFrs");
                }
                return _CategoriesFrs;
            }
        }
        private ObjectSet<CategoriesFr> _CategoriesFrs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CategoriesSp> CategoriesSps
        {
            get
            {
                if ((_CategoriesSps == null))
                {
                    _CategoriesSps = base.CreateObjectSet<CategoriesSp>("CategoriesSps");
                }
                return _CategoriesSps;
            }
        }
        private ObjectSet<CategoriesSp> _CategoriesSps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AutomatedMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutomatedMessages(AutomatedMessage automatedMessage)
        {
            base.AddObject("AutomatedMessages", automatedMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AutomationEmailProblems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutomationEmailProblems(AutomationEmailProblem automationEmailProblem)
        {
            base.AddObject("AutomationEmailProblems", automationEmailProblem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CitiesUpdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCitiesUpdates(CitiesUpdate citiesUpdate)
        {
            base.AddObject("CitiesUpdates", citiesUpdate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CountriesUpdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountriesUpdates(CountriesUpdate countriesUpdate)
        {
            base.AddObject("CountriesUpdates", countriesUpdate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the regionsUpdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToregionsUpdates(regionsUpdate regionsUpdate)
        {
            base.AddObject("regionsUpdates", regionsUpdate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CanadaZipCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCanadaZipCodes(CanadaZipCode canadaZipCode)
        {
            base.AddObject("CanadaZipCodes", canadaZipCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USAZipCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSAZipCodes(USAZipCode uSAZipCode)
        {
            base.AddObject("USAZipCodes", uSAZipCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoriesFrs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoriesFrs(CategoriesFr categoriesFr)
        {
            base.AddObject("CategoriesFrs", categoriesFr);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CategoriesSps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoriesSps(CategoriesSp categoriesSp)
        {
            base.AddObject("CategoriesSps", categoriesSp);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="AutomatedMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AutomatedMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AutomatedMessage object.
        /// </summary>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        public static AutomatedMessage CreateAutomatedMessage(global::System.Int32 messageID)
        {
            AutomatedMessage automatedMessage = new AutomatedMessage();
            automatedMessage.MessageID = messageID;
            return automatedMessage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                if (_MessageID != value)
                {
                    OnMessageIDChanging(value);
                    ReportPropertyChanging("MessageID");
                    _MessageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MessageID");
                    OnMessageIDChanged();
                }
            }
        }
        private global::System.Int32 _MessageID;
        partial void OnMessageIDChanging(global::System.Int32 value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="AutomationEmailProblem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AutomationEmailProblem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AutomationEmailProblem object.
        /// </summary>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        public static AutomationEmailProblem CreateAutomationEmailProblem(global::System.Int32 messageID)
        {
            AutomationEmailProblem automationEmailProblem = new AutomationEmailProblem();
            automationEmailProblem.MessageID = messageID;
            return automationEmailProblem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                if (_MessageID != value)
                {
                    OnMessageIDChanging(value);
                    ReportPropertyChanging("MessageID");
                    _MessageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MessageID");
                    OnMessageIDChanged();
                }
            }
        }
        private global::System.Int32 _MessageID;
        partial void OnMessageIDChanging(global::System.Int32 value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="CanadaZipCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CanadaZipCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CanadaZipCode object.
        /// </summary>
        /// <param name="postalCodeID">Initial value of the PostalCodeID property.</param>
        /// <param name="postalCode">Initial value of the PostalCode property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="province">Initial value of the Province property.</param>
        /// <param name="provinceCode">Initial value of the ProvinceCode property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        public static CanadaZipCode CreateCanadaZipCode(global::System.Int32 postalCodeID, global::System.String postalCode, global::System.String city, global::System.String province, global::System.String provinceCode, global::System.String type, global::System.Decimal latitude, global::System.Decimal longitude)
        {
            CanadaZipCode canadaZipCode = new CanadaZipCode();
            canadaZipCode.PostalCodeID = postalCodeID;
            canadaZipCode.PostalCode = postalCode;
            canadaZipCode.City = city;
            canadaZipCode.Province = province;
            canadaZipCode.ProvinceCode = provinceCode;
            canadaZipCode.Type = type;
            canadaZipCode.Latitude = latitude;
            canadaZipCode.Longitude = longitude;
            return canadaZipCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostalCodeID
        {
            get
            {
                return _PostalCodeID;
            }
            set
            {
                if (_PostalCodeID != value)
                {
                    OnPostalCodeIDChanging(value);
                    ReportPropertyChanging("PostalCodeID");
                    _PostalCodeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostalCodeID");
                    OnPostalCodeIDChanged();
                }
            }
        }
        private global::System.Int32 _PostalCodeID;
        partial void OnPostalCodeIDChanging(global::System.Int32 value);
        partial void OnPostalCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProvinceCode
        {
            get
            {
                return _ProvinceCode;
            }
            set
            {
                OnProvinceCodeChanging(value);
                ReportPropertyChanging("ProvinceCode");
                _ProvinceCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProvinceCode");
                OnProvinceCodeChanged();
            }
        }
        private global::System.String _ProvinceCode;
        partial void OnProvinceCodeChanging(global::System.String value);
        partial void OnProvinceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="CategoriesFr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoriesFr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoriesFr object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static CategoriesFr CreateCategoriesFr(global::System.Int32 categoryID, global::System.String categoryName)
        {
            CategoriesFr categoriesFr = new CategoriesFr();
            categoriesFr.CategoryID = categoryID;
            categoriesFr.CategoryName = categoryName;
            return categoriesFr;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="CategoriesSp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoriesSp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CategoriesSp object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static CategoriesSp CreateCategoriesSp(global::System.Int32 categoryID, global::System.String categoryName)
        {
            CategoriesSp categoriesSp = new CategoriesSp();
            categoriesSp.CategoryID = categoryID;
            categoriesSp.CategoryName = categoryName;
            return categoriesSp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static Category CreateCategory(global::System.Int32 categoryID, global::System.String categoryName)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.CategoryName = categoryName;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="CitiesUpdate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CitiesUpdate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CitiesUpdate object.
        /// </summary>
        /// <param name="cityId">Initial value of the CityId property.</param>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        public static CitiesUpdate CreateCitiesUpdate(global::System.Int32 cityId, global::System.Int32 countryId)
        {
            CitiesUpdate citiesUpdate = new CitiesUpdate();
            citiesUpdate.CityId = cityId;
            citiesUpdate.CountryId = countryId;
            return citiesUpdate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                if (_CityId != value)
                {
                    OnCityIdChanging(value);
                    ReportPropertyChanging("CityId");
                    _CityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CityId");
                    OnCityIdChanged();
                }
            }
        }
        private global::System.Int32 _CityId;
        partial void OnCityIdChanging(global::System.Int32 value);
        partial void OnCityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private global::System.Int32 _CountryId;
        partial void OnCountryIdChanging(global::System.Int32 value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RegionId
        {
            get
            {
                return _RegionId;
            }
            set
            {
                OnRegionIdChanging(value);
                ReportPropertyChanging("RegionId");
                _RegionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegionId");
                OnRegionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RegionId;
        partial void OnRegionIdChanging(Nullable<global::System.Int32> value);
        partial void OnRegionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeZone
        {
            get
            {
                return _TimeZone;
            }
            set
            {
                OnTimeZoneChanging(value);
                ReportPropertyChanging("TimeZone");
                _TimeZone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeZone");
                OnTimeZoneChanged();
            }
        }
        private global::System.String _TimeZone;
        partial void OnTimeZoneChanging(global::System.String value);
        partial void OnTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SidejobModel", "FK_CitiesUpdate_regionsUpdate", "regionsUpdate")]
        public regionsUpdate regionsUpdate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<regionsUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "regionsUpdate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<regionsUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "regionsUpdate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<regionsUpdate> regionsUpdateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<regionsUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "regionsUpdate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<regionsUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "regionsUpdate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="CountriesUpdate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CountriesUpdate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CountriesUpdate object.
        /// </summary>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        public static CountriesUpdate CreateCountriesUpdate(global::System.Int32 countryId)
        {
            CountriesUpdate countriesUpdate = new CountriesUpdate();
            countriesUpdate.CountryId = countryId;
            return countriesUpdate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                if (_CountryId != value)
                {
                    OnCountryIdChanging(value);
                    ReportPropertyChanging("CountryId");
                    _CountryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CountryId");
                    OnCountryIdChanged();
                }
            }
        }
        private global::System.Int32 _CountryId;
        partial void OnCountryIdChanging(global::System.Int32 value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIPS104
        {
            get
            {
                return _FIPS104;
            }
            set
            {
                OnFIPS104Changing(value);
                ReportPropertyChanging("FIPS104");
                _FIPS104 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIPS104");
                OnFIPS104Changed();
            }
        }
        private global::System.String _FIPS104;
        partial void OnFIPS104Changing(global::System.String value);
        partial void OnFIPS104Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISO2
        {
            get
            {
                return _ISO2;
            }
            set
            {
                OnISO2Changing(value);
                ReportPropertyChanging("ISO2");
                _ISO2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISO2");
                OnISO2Changed();
            }
        }
        private global::System.String _ISO2;
        partial void OnISO2Changing(global::System.String value);
        partial void OnISO2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISO3
        {
            get
            {
                return _ISO3;
            }
            set
            {
                OnISO3Changing(value);
                ReportPropertyChanging("ISO3");
                _ISO3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISO3");
                OnISO3Changed();
            }
        }
        private global::System.String _ISO3;
        partial void OnISO3Changing(global::System.String value);
        partial void OnISO3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISON
        {
            get
            {
                return _ISON;
            }
            set
            {
                OnISONChanging(value);
                ReportPropertyChanging("ISON");
                _ISON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISON");
                OnISONChanged();
            }
        }
        private global::System.String _ISON;
        partial void OnISONChanging(global::System.String value);
        partial void OnISONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Internet
        {
            get
            {
                return _Internet;
            }
            set
            {
                OnInternetChanging(value);
                ReportPropertyChanging("Internet");
                _Internet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Internet");
                OnInternetChanged();
            }
        }
        private global::System.String _Internet;
        partial void OnInternetChanging(global::System.String value);
        partial void OnInternetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Capital
        {
            get
            {
                return _Capital;
            }
            set
            {
                OnCapitalChanging(value);
                ReportPropertyChanging("Capital");
                _Capital = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Capital");
                OnCapitalChanged();
            }
        }
        private global::System.String _Capital;
        partial void OnCapitalChanging(global::System.String value);
        partial void OnCapitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MapReference
        {
            get
            {
                return _MapReference;
            }
            set
            {
                OnMapReferenceChanging(value);
                ReportPropertyChanging("MapReference");
                _MapReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MapReference");
                OnMapReferenceChanged();
            }
        }
        private global::System.String _MapReference;
        partial void OnMapReferenceChanging(global::System.String value);
        partial void OnMapReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NationalitySingular
        {
            get
            {
                return _NationalitySingular;
            }
            set
            {
                OnNationalitySingularChanging(value);
                ReportPropertyChanging("NationalitySingular");
                _NationalitySingular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NationalitySingular");
                OnNationalitySingularChanged();
            }
        }
        private global::System.String _NationalitySingular;
        partial void OnNationalitySingularChanging(global::System.String value);
        partial void OnNationalitySingularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NationalityPlural
        {
            get
            {
                return _NationalityPlural;
            }
            set
            {
                OnNationalityPluralChanging(value);
                ReportPropertyChanging("NationalityPlural");
                _NationalityPlural = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NationalityPlural");
                OnNationalityPluralChanged();
            }
        }
        private global::System.String _NationalityPlural;
        partial void OnNationalityPluralChanging(global::System.String value);
        partial void OnNationalityPluralChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencyCode
        {
            get
            {
                return _CurrencyCode;
            }
            set
            {
                OnCurrencyCodeChanging(value);
                ReportPropertyChanging("CurrencyCode");
                _CurrencyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrencyCode");
                OnCurrencyCodeChanged();
            }
        }
        private global::System.String _CurrencyCode;
        partial void OnCurrencyCodeChanging(global::System.String value);
        partial void OnCurrencyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Population
        {
            get
            {
                return _Population;
            }
            set
            {
                OnPopulationChanging(value);
                ReportPropertyChanging("Population");
                _Population = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Population");
                OnPopulationChanged();
            }
        }
        private Nullable<global::System.Int64> _Population;
        partial void OnPopulationChanging(Nullable<global::System.Int64> value);
        partial void OnPopulationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContinentReference
        {
            get
            {
                return _ContinentReference;
            }
            set
            {
                OnContinentReferenceChanging(value);
                ReportPropertyChanging("ContinentReference");
                _ContinentReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContinentReference");
                OnContinentReferenceChanged();
            }
        }
        private global::System.String _ContinentReference;
        partial void OnContinentReferenceChanging(global::System.String value);
        partial void OnContinentReferenceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SidejobModel", "FK_regionsUpdate_CountriesUpdate", "regionsUpdate")]
        public EntityCollection<regionsUpdate> regionsUpdates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<regionsUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "regionsUpdate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<regionsUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "regionsUpdate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="regionsUpdate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class regionsUpdate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new regionsUpdate object.
        /// </summary>
        /// <param name="regionId">Initial value of the RegionId property.</param>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        public static regionsUpdate CreateregionsUpdate(global::System.Int32 regionId, global::System.Int32 countryId)
        {
            regionsUpdate regionsUpdate = new regionsUpdate();
            regionsUpdate.RegionId = regionId;
            regionsUpdate.CountryId = countryId;
            return regionsUpdate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RegionId
        {
            get
            {
                return _RegionId;
            }
            set
            {
                if (_RegionId != value)
                {
                    OnRegionIdChanging(value);
                    ReportPropertyChanging("RegionId");
                    _RegionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegionId");
                    OnRegionIdChanged();
                }
            }
        }
        private global::System.Int32 _RegionId;
        partial void OnRegionIdChanging(global::System.Int32 value);
        partial void OnRegionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private global::System.Int32 _CountryId;
        partial void OnCountryIdChanging(global::System.Int32 value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADM1Code
        {
            get
            {
                return _ADM1Code;
            }
            set
            {
                OnADM1CodeChanging(value);
                ReportPropertyChanging("ADM1Code");
                _ADM1Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADM1Code");
                OnADM1CodeChanged();
            }
        }
        private global::System.String _ADM1Code;
        partial void OnADM1CodeChanging(global::System.String value);
        partial void OnADM1CodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SidejobModel", "FK_CitiesUpdate_regionsUpdate", "CitiesUpdate")]
        public EntityCollection<CitiesUpdate> CitiesUpdates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CitiesUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "CitiesUpdate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CitiesUpdate>("SidejobModel.FK_CitiesUpdate_regionsUpdate", "CitiesUpdate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SidejobModel", "FK_regionsUpdate_CountriesUpdate", "CountriesUpdate")]
        public CountriesUpdate CountriesUpdate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountriesUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "CountriesUpdate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountriesUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "CountriesUpdate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CountriesUpdate> CountriesUpdateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CountriesUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "CountriesUpdate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CountriesUpdate>("SidejobModel.FK_regionsUpdate_CountriesUpdate", "CountriesUpdate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SidejobModel", Name="USAZipCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USAZipCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USAZipCode object.
        /// </summary>
        /// <param name="postalCodeID">Initial value of the PostalCodeID property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="county">Initial value of the County property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static USAZipCode CreateUSAZipCode(global::System.Int32 postalCodeID, global::System.String city, global::System.String state, global::System.String county, global::System.String type)
        {
            USAZipCode uSAZipCode = new USAZipCode();
            uSAZipCode.PostalCodeID = postalCodeID;
            uSAZipCode.City = city;
            uSAZipCode.State = state;
            uSAZipCode.County = county;
            uSAZipCode.Type = type;
            return uSAZipCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostalCodeID
        {
            get
            {
                return _PostalCodeID;
            }
            set
            {
                if (_PostalCodeID != value)
                {
                    OnPostalCodeIDChanging(value);
                    ReportPropertyChanging("PostalCodeID");
                    _PostalCodeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostalCodeID");
                    OnPostalCodeIDChanged();
                }
            }
        }
        private global::System.Int32 _PostalCodeID;
        partial void OnPostalCodeIDChanging(global::System.Int32 value);
        partial void OnPostalCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _County;
            }
            set
            {
                OnCountyChanging(value);
                ReportPropertyChanging("County");
                _County = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("County");
                OnCountyChanged();
            }
        }
        private global::System.String _County;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
    }

    #endregion
    
}
